#!/usr/bin/env python3
"""
symmetric_search.py, find logical operators fixed by a translation subgroup.

WHY
---
The open enumeration found two orbits of 144, giving 288 weight-18 X-logicals
for the two-gross code, against the 336 quoted in Tour de gross Figure 12. The
shortfall is 48, and 48 = 144/3, so the missing operators form an orbit whose
stabiliser has order 3: they are invariant under some translation of order 3.

That is a constraint, not a mystery, and constraints make integer programs
easier rather than harder. Imposing v = g(v) for a generator g of order 3 ties
the 288 variables into 96 free groups. The resulting program is small enough to
solve to proven optimality in seconds, where the unconstrained version times
out.

The order-3 subgroups of Z_12 x Z_12 are generated by (4,0), (0,4), (4,4) and
(4,8). We try each.

This is the same lesson as the main UGP: when a search is too big, the
structure of the object usually tells you which slice to look in.
"""

from __future__ import annotations

import numpy as np
from scipy.optimize import Bounds, LinearConstraint, milp
from scipy.sparse import csc_matrix

from bbcode import build
from distance import z_logical_basis
from enumerate_weight import orbit, translations
from paths import data


def shift_perm(code, a, b):
    """Index permutation for the translation x^a y^b."""
    l, m, half = code.l, code.m, code.l * code.m
    bi, bj = np.divmod(np.arange(half), m)
    dest = ((bi + a) % l) * m + ((bj + b) % m)
    p = np.empty(2 * half, dtype=np.int64)
    p[dest] = np.arange(half)
    p[dest + half] = np.arange(half) + half
    return p


def solve_symmetric(code, lz_row, gen, weight, time_limit=60.0):
    """Min-weight logical invariant under `gen`, pinned to `weight`."""
    n, mz = code.n, code.HZ.shape[0]
    nsl = mz + 1
    p = shift_perm(code, *gen)

    rows, lows, ups = [], [], []

    # H_Z v - 2 s = 0
    for r in range(mz):
        row = np.zeros(n + nsl)
        row[:n] = code.HZ[r]
        row[n + r] = -2.0
        rows.append(row); lows.append(0.0); ups.append(0.0)

    # anticommute with this Z-logical
    row = np.zeros(n + nsl)
    row[:n] = lz_row
    row[n + mz] = -2.0
    rows.append(row); lows.append(1.0); ups.append(1.0)

    # weight pinned
    row = np.zeros(n + nsl); row[:n] = 1.0
    rows.append(row); lows.append(float(weight)); ups.append(float(weight))

    # invariance: v_i = v_{p(i)} for every i
    for i in range(n):
        if p[i] == i:
            continue
        row = np.zeros(n + nsl)
        row[i] = 1.0
        row[p[i]] = -1.0
        rows.append(row); lows.append(0.0); ups.append(0.0)

    A = csc_matrix(np.array(rows))
    cons = [LinearConstraint(A, np.array(lows), np.array(ups))]
    res = milp(c=np.concatenate([np.ones(n), np.zeros(nsl)]),
               constraints=cons, integrality=np.ones(n + nsl),
               bounds=Bounds(np.zeros(n + nsl),
                             np.concatenate([np.ones(n), np.full(nsl, np.inf)])),
               options=dict(time_limit=time_limit, mip_rel_gap=0.0))
    if res.x is None:
        return None, int(res.status)
    return np.round(res.x[:n]).astype(np.uint8), int(res.status)


if __name__ == "__main__":
    import json

    W = 18
    code = build("two-gross", 1)
    lz = z_logical_basis(code)
    perms = translations(code)

    found = set()
    try:
        st = json.load(open(data("weight18_two-gross_orbits.json")))
        found = {bytes.fromhex(h) for h in st["found"]}
        print(f"  resumed with {len(found)} operators")
    except FileNotFoundError:
        pass

    GENS = [(4, 0), (0, 4), (4, 4), (4, 8), (8, 0), (0, 8)]
    for gen in GENS:
        for j in range(len(lz)):
            v, status = solve_symmetric(code, lz[j], gen, W, time_limit=20.0)
            if v is None:
                continue
            orb = orbit(v, perms)
            new = orb - found
            if new:
                found |= new
                print(f"  gen {gen} class {j:2d}: orbit size {len(orb):3d}, "
                      f"+{len(new):3d}  ->  total {len(found)}")
    json.dump({"found": [b.hex() for b in found], "weight": W},
              open(data("weight18_two-gross_orbits.json"), "w"))
    print(f"\n  weight-18 X-logicals found so far: {len(found)}")
